#!/usr/bin/env bash
set -euo pipefail

log() {
  printf '[scaffold_mv3] %s\n' "$1"
}

usage() {
  cat <<'EOF'
Usage:
  scaffold_mv3.sh <target-dir> [extension-name] [host-match]

Example:
  scaffold_mv3.sh ./my-extension "My Extension" "https://example.com/*"
EOF
}

write_if_absent() {
  local filepath="$1"
  local content="$2"

  if [ -e "$filepath" ]; then
    log "skip existing file: $filepath"
    return 0
  fi

  printf '%s' "$content" >"$filepath"
  log "created file: $filepath"
}

main() {
  if [ "$#" -lt 1 ]; then
    usage
    exit 1
  fi

  local target_dir="$1"
  local ext_name="${2:-MV3 Starter}"
  local host_match="${3:-https://*/*}"

  mkdir -p "$target_dir/background" "$target_dir/content" "$target_dir/popup" "$target_dir/options"
  log "created directories under: $target_dir"

  write_if_absent "$target_dir/manifest.json" "$(cat <<EOF
{
  "manifest_version": 3,
  "name": "$ext_name",
  "version": "0.1.0",
  "description": "Generated by scaffold_mv3.sh",
  "permissions": ["storage", "tabs"],
  "host_permissions": ["$host_match"],
  "background": {
    "service_worker": "background/service-worker.js",
    "type": "module"
  },
  "action": {
    "default_title": "$ext_name",
    "default_popup": "popup/popup.html"
  },
  "options_page": "options/options.html",
  "content_scripts": [
    {
      "matches": ["$host_match"],
      "js": ["content/content.js"],
      "run_at": "document_idle"
    }
  ]
}
EOF
)"

  write_if_absent "$target_dir/background/service-worker.js" "$(cat <<'EOF'
chrome.runtime.onInstalled.addListener(() => {
  console.log("[background] extension installed");
});

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (!message || !message.type) {
    sendResponse({ ok: false, error: "invalid message" });
    return;
  }

  if (message.type === "PING") {
    sendResponse({ ok: true, from: "service-worker", tabId: sender?.tab?.id ?? null });
    return;
  }

  sendResponse({ ok: false, error: "unsupported type" });
});
EOF
)"

  write_if_absent "$target_dir/content/content.js" "$(cat <<'EOF'
(() => {
  chrome.runtime.sendMessage({ type: "PING" }, (response) => {
    if (chrome.runtime.lastError) {
      console.warn("[content] message failed:", chrome.runtime.lastError.message);
      return;
    }
    console.log("[content] response:", response);
  });
})();
EOF
)"

  write_if_absent "$target_dir/popup/popup.html" "$(cat <<'EOF'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>Popup</title>
    <link rel="stylesheet" href="./popup.css" />
  </head>
  <body>
    <main>
      <h1>MV3 Starter</h1>
      <button id="ping-btn">Ping Background</button>
      <pre id="output"></pre>
    </main>
    <script src="./popup.js"></script>
  </body>
</html>
EOF
)"

  write_if_absent "$target_dir/popup/popup.css" "$(cat <<'EOF'
body {
  margin: 0;
  font-family: sans-serif;
  min-width: 280px;
}

main {
  padding: 12px;
}

button {
  width: 100%;
  margin-top: 8px;
}

pre {
  white-space: pre-wrap;
  word-break: break-word;
  margin-top: 8px;
}
EOF
)"

  write_if_absent "$target_dir/popup/popup.js" "$(cat <<'EOF'
const button = document.getElementById("ping-btn");
const output = document.getElementById("output");

button.addEventListener("click", () => {
  chrome.runtime.sendMessage({ type: "PING" }, (response) => {
    if (chrome.runtime.lastError) {
      output.textContent = `error: ${chrome.runtime.lastError.message}`;
      return;
    }
    output.textContent = JSON.stringify(response, null, 2);
  });
});
EOF
)"

  write_if_absent "$target_dir/options/options.html" "$(cat <<'EOF'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>Options</title>
  </head>
  <body>
    <h1>Options</h1>
    <p>Edit options page as needed.</p>
  </body>
</html>
EOF
)"

  log "done. load extension from: $target_dir"
}

main "$@"
